# Generated by Django 3.1.1 on 2021-02-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default='lorem', max_length=100, unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
