# Generated by Django 3.1.1 on 2021-02-18 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20210217_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={},
        ),
        migrations.RemoveField(
            model_name='thread',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='author',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='body',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='created',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='views',
        ),
    ]
