# Generated by Django 3.1.1 on 2021-02-18 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0006_auto_20210217_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-modified'], 'verbose_name': 'Tópico', 'verbose_name_plural': 'Tópicos'},
        ),
        migrations.AddField(
            model_name='thread',
            name='answers',
            field=models.IntegerField(blank=True, default=0, verbose_name='Respostas'),
        ),
        migrations.AddField(
            model_name='thread',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='threads', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='thread',
            name='body',
            field=models.TextField(default='', verbose_name='Mensagem'),
        ),
        migrations.AddField(
            model_name='thread',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado em'),
        ),
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default='', max_length=100, verbose_name='Identificador'),
        ),
        migrations.AddField(
            model_name='thread',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='thread',
            name='views',
            field=models.IntegerField(blank=True, default=0, verbose_name='Visualizações'),
        ),
    ]
